In [1]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import MultinomialNB

from sklearn.svm import LinearSVC

from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import StackingClassifier

from xgboost import XGBClassifier

from sklearn.pipeline import Pipeline

from sklearn.metrics import classification_report

In [2]:
#load data
df = pd.read_csv("/home/sahil-gaund/Desktop/scamshield-ai/datasets/processed/cleaned_spam.csv")
df.head()

,label,message,clean_message
0,spam,Congratulations! You've been selected for a lu...,congratul select luxuri vacat getaway claim prize
1,spam,URGENT: Your account has been compromised. Cli...,urgent account compromis click reset password ...
2,spam,You've won a free iPhone! Claim your prize by ...,free iphon claim prize click link
3,spam,Act now and receive a 50% discount on all purc...,act receiv discount purchas limit time offer
4,spam,Important notice: Your subscription will expir...,import notic subscript expir soon renew avoid ...

In [3]:
df['label'] = df['label'].map({'ham':0, 'spam':1})

In [4]:
df.head()

,label,message,clean_message
0,1,Congratulations! You've been selected for a lu...,congratul select luxuri vacat getaway claim prize
1,1,URGENT: Your account has been compromised. Cli...,urgent account compromis click reset password ...
2,1,You've won a free iPhone! Claim your prize by ...,free iphon claim prize click link
3,1,Act now and receive a 50% discount on all purc...,act receiv discount purchas limit time offer
4,1,Important notice: Your subscription will expir...,import notic subscript expir soon renew avoid ...

In [15]:
# REMOVE NULL VALUES
df.dropna(inplace=True)

# CONVERT TO STRING

df['clean_message'] = df['clean_message'].astype(str)

# FEATURES & TARGET

X = df['clean_message']

y = df['label']

In [16]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
#TF-IDf
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))

In [18]:
#base model 
base_models = [
    ('lr', LogisticRegression()),
    
    ('nb', MultinomialNB()),
    
    ('svm', LinearSVC()),
    
    ('rf', RandomForestClassifier())
]

In [19]:
#meta model 
meta_model = XGBClassifier(eval_metric='logloss')

In [20]:
#stacking ensemble
stack_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

In [21]:
#final pipline 
pipeline = Pipeline([
    ('tfidf', tfidf),
    ('model', stack_model)
])

In [22]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=5000, ngram_range=(1, 2))),
                ('model',
                 StackingClassifier(cv=5,
                                    estimators=[('lr', LogisticRegression()),
                                                ('nb', MultinomialNB()),
                                                ('svm', LinearSVC()),
                                                ('rf',
                                                 RandomForestClassifier())],
                                    final_estimator=XGBClassifier(base_score=None,
                                                                  booster=None,
                                                                  callbacks=None,
                                                                  colsample_bylevel=None,
                                                                  colsample_bynode=None,
                                                                  col...
                                                                  feature_weights=None,
                                                                  gamma=None,
                                                                  grow_policy=None,
                                                                  importance_type=None,
                                                                  interaction_constraints=None,
                                                                  learning_rate=None,
                                                                  max_bin=None,
                                                                  max_cat_threshold=None,
                                                                  max_cat_to_onehot=None,
                                                                  max_delta_step=None,
                                                                  max_depth=None,
                                                                  max_leaves=None,
                                                                  min_child_weight=None,
                                                                  missing=nan,
                                                                  monotone_constraints=None,
                                                                  multi_strategy=None,
                                                                  n_estimators=None,
                                                                  n_jobs=None,
                                                                  num_parallel_tree=None, ...)))])

In [23]:
#predticiions

y_pred = pipeline.predict(X_test)

In [24]:
#evaluation
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1710
           1       0.93      0.89      0.91       477

    accuracy                           0.96      2187
   macro avg       0.95      0.94      0.94      2187
weighted avg       0.96      0.96      0.96      2187

In [25]:
joblib.dump(
    pipeline,"/home/sahil-gaund/Desktop/scamshield-ai/ml/models/scamshield_model.pkl"
)
print("model saved")

model saved

In [26]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Precision:", precision_score(y_test, y_pred))

print("Recall:", recall_score(y_test, y_pred))

print("F1:", f1_score(y_test, y_pred))

print("ROC AUC:", roc_auc_score(y_test, y_pred))

Accuracy: 0.9615912208504801
Precision: 0.9281045751633987
Recall: 0.8930817610062893
F1: 0.9102564102564102
ROC AUC: 0.9368917576961272